# Generated by Django 3.2.4 on 2022-04-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='korporativcategory',
            options={'ordering': ['-title']},
        ),
    ]
